### ISSUE TITLE
Split error while trying to generate new app

### ISSUE THREAD

**Issue by StephD** [drnic/appscrolls#20]
Hello, 

Following the website instructions, I just have install the gem appscrolls, and when i trying to generate a new projet ( ' scrolls new mynewapp  ' ) , I'm getting an ArgumentError.

/lib/appscrolls/scroll.rb:30:in `split': invalid byte sequence in US-ASCII (ArgumentError)

http://pastebin.com/MMaG4fkG

Does someone have any answer to this problem?

Thanks

**Comment by drnic** [comment]
Oh no. Hmm, I wonder how to reproduce that locally. I'll try later. 

Would you like to try upgrading to latest ruby 1.9.3 also and see if that resolves it? 

Cheers
Nic

Dr Nic Williams - VP Engineering
Engine Yard
The Leading Platform as a Service
Mobile: +1 415 860 2185
Skype: nicwilliams
Twitter: @drnic

**Comment by StephD** [comment]
Thanks

Brew seems to don't upgrade the ruby version from 1.9.3p0 to 1.9.3p125. I prefer not manipulate too much my package because I'm still a beginner into os x world, sorry.

EDIT : I just try with ruby 1.9.3p125, and it's the same thing : 
% scrolls new my_app
/Users/mini2/.rvm/gems/ruby-1.9.3-p125/gems/appscrolls-0.8.3/lib/appscrolls/scroll.rb:30:in `split': invalid byte sequence in US-ASCII (ArgumentError)

I'll let you take a look localy, I'm not in a hurry.

**Comment by ghost** [comment]
Same here, fresh RVM install with latest ruby 1.9.3-p194 + rails 3.2.3 with appscrolls 0.8.3

https://gist.github.com/2481686

**Comment by swade1987** [comment]
Issues go stale after 60d of inactivity.
